version: '3'
services:
  www:
      build:
        context: .
        dockerfile: Dockerfile
      volumes:
        - "./:/var/www/html"
      ports:
        - 80:80
        - 443:443

  db: 
    image: mysql:latest
    environment:
      - MYSQL_DATABASE=php_docker
      - MYSQL_USER=php_docker
      - MYSQL_PASSWORD=password
      - MYSQL_ALLOW_EMPTY_PASSWORD=1
    volumes:
      - "./db:/docker-entrypoint-initdb.d"
      - "mysql-data:/var/lib/mysql"  # Add this line to persist MySQL data

  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    ports:
      - 8001:80
    environment:
      - PMA_HOST=db
      - PMA_PORT=3306

volumes:
  mysql-data:  # Define a named volume for MySQL data
